package com.cesaco.mobias.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * Entity implementation class for Entity: Users
 * 
 */
@Entity
public class JAAS_User implements Serializable {

	@Column(unique=true)
	private String username;
	@NotNull
	private String Nome;
	@NotNull
	private String Cognome;
	private String Azienda;

	@Transient
	private String stringRoles;

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private List<JAAS_Role> roles;

	public List<JAAS_Role> getRoles() {
		return roles;
	}

	public String getStringRoles() {
		String roless = "";
		if (roles != null) {
			for (JAAS_Role role : roles) {
				roless += role.getRoles() + " ";
			}
		}
		return roless;
	}

	public void setStringRoles(String stringRoles) {
		this.stringRoles = stringRoles;
	}

	public void setRoles(List<JAAS_Role> roles) {
		if (roles == null) {
			roles = new ArrayList<JAAS_Role>();
		}
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id")
	private int id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNome() {
		return Nome;
	}

	public void setNome(String nome) {
		Nome = nome;
	}

	public String getCognome() {
		return Cognome;
	}

	public void setCognome(String cognome) {
		Cognome = cognome;
	}

	public String getAzienda() {
		return Azienda;
	}

	public void setAzienda(String azienda) {
		Azienda = azienda;
	}

	@NotNull
	private String password;
	private static final long serialVersionUID = 1L;

	public JAAS_User() {
		super();
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	private String[] favRoles;

	public String[] getFavRoles() {
		return favRoles;
	}

	public void setFavRoles(String[] favRoles) {
		this.favRoles = favRoles;
		roles = new ArrayList<JAAS_Role>();
		for (String role : favRoles) {
			JAAS_Role jaas_Role = new JAAS_Role();
			jaas_Role.setUsername(this.username);
			jaas_Role.setRole_group("Roles");
			jaas_Role.setRoles(role);
			roles.add(jaas_Role);
		}
	}

	// Generated by Map
	private static Map<String, Object> rolesValue;
	static {
		rolesValue = new LinkedHashMap<String, Object>();
		rolesValue.put("admin", "admin"); // label, value
		rolesValue.put("user", "user");
	}

	public Map<String, Object> getRolesValue() {
		return rolesValue;
	}

	public String getRolesValueInString() {
		return Arrays.toString(favRoles);
	}

	// public void setRoles(String roles) {
	// }

	// public String getRoles() {
	// roles = "";
	// // @SuppressWarnings("unchecked")
	// // final List<JAAS_Role> candidates = em.createQuery(
	// // "select m " + "from JAAS_Role m " + "where m.username='"
	// // + this.username + "'").getResultList();
	// //
	// // if (candidates.isEmpty()) {
	// //
	// // } else {
	// // for (JAAS_Role role : candidates) {
	// // roles += role.getRoles() + " ";
	// // }
	// //
	// // }
	//
	// return roles;
	// }

}
